version: "3.9"
services:
  mongo:
    image: mongo:7.0.0-rc7
    ports:
      - "5432:5432"
    container_name: "mongo"
    restart: always
    volumes:
      - /backend/data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - 8081:8081
    container_name: "mongo-express"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.production
    depends_on:
      - mongo
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      NODE_ENV: "production"
volumes:
  /backend/data/db:
